package router

import (
	"cgin/conf"
	"cgin/controller"
	_ "cgin/docs" // docs is generated by Swag CLI, you have to import it.
	"cgin/middleware"
	"github.com/gin-contrib/gzip"
	"github.com/gin-gonic/gin"
	swaggerFiles "github.com/swaggo/files"
	ginSwagger "github.com/swaggo/gin-swagger"
)

const (
	Version = "v1"

	RootApiPrefix = "/api/" + Version
	AuthPrefix    = RootApiPrefix + "/auth"
	Student       = RootApiPrefix + "/students"
	MiniProgram   = RootApiPrefix + "/mini_program"
	Trigger       = RootApiPrefix + "/trigger/"
	Thinking      = RootApiPrefix + "/thinking"
	Score         = RootApiPrefix + "/scores"

)

func MapRoute() *gin.Engine {

	router := gin.New()
	// 全局的中间件
	router.Use(gzip.Gzip(gzip.DefaultCompression), middleware.BusinessErrorHandler())

	// dev export swagger api.
	if conf.AppEnvDev == conf.AppConfig.DefaultString(conf.AppEnvironment, conf.AppEnvProd) {
		router.GET("/swagger/*any", ginSwagger.DisablingWrapHandler(swaggerFiles.Handler, "xx"))
	}

	mapNormalRouter(router)
	mapStudentRouter(router)
	mapStaticRouter(router)
	mapMiniProgramRouter(router)
	mapTaskRouter(router)
	mapThinkingRouter(router)

	// 认证业务的逻辑 API
	// api/auth
	apiAuth := router.Group(AuthPrefix).Use(middleware.Auth)
	{
		// 需要进行认证的业务API
		apiAuth.POST("/me", controller.AuthController.Me)
	}

	// api/auth
	apiNotAuth := router.Group(AuthPrefix)
	{
		// 不需要进行认证的API
		apiNotAuth.POST("/login", controller.AuthController.Login)
	}

	// 普通的资源
	// api/
	apiNormal := router.Group(RootApiPrefix)
	{
		apiNormal.POST("/send_template_msg", controller.MiniProgramController.SendTemplateMsg)
		apiNormal.POST("/decode_verify_code", controller.VerifyCodeCtl.Recognize)
		apiNormal.GET("/daily/image", controller.DailyController.GetImage)
		apiNormal.GET("/daily/sentence", controller.DailyController.GetSentence)
	}

	return router
}
