package router

import (
	"cgin/conf"
	_ "cgin/docs" // docs is generated by Swag CLI, you have to import it.
	"cgin/middleware"
	"github.com/gin-contrib/gzip"
	"github.com/gin-gonic/gin"
	swaggerFiles "github.com/swaggo/files"
	ginSwagger "github.com/swaggo/gin-swagger"
)

const (
	Version = "v1"

	RootApiPrefix = "/api/" + Version
	AuthPrefix    = RootApiPrefix + "/auth"
	Student       = RootApiPrefix + "/students"
	MiniProgram   = RootApiPrefix + "/mini_program"
	Trigger       = RootApiPrefix + "/trigger/"
	Thinking      = RootApiPrefix + "/thinking"
	Score         = RootApiPrefix + "/scores"
)

func InitRouter() *gin.Engine {
	router := gin.New()
	// 全局的中间件
	router.Use(gzip.Gzip(gzip.DefaultCompression), middleware.BusinessErrorHandler())
	// dev export swagger api.
	if conf.IsDev() {
		router.Use(middleware.AllowCors()) // 允许跨域 正式环境配置nginx不跨域
		router.GET("/swagger/*any", ginSwagger.DisablingWrapHandler(swaggerFiles.Handler, "xx"))
	}

	initNormalRouter(router)
	initStudentRouter(router)
	initStaticRouter(router)
	initMiniProgramRouter(router)
	initTaskRouter(router)
	initThinkingRouter(router)
	initScoresRouter(router)
	initAuthRouter(router)

	return router
}
