// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag at
// 2020-03-12 15:14:47.5263673 +0800 CST m=+3.167099801

package docs

import (
	"bytes"
	"encoding/json"
	"strings"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{.Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "license": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/login": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "登录",
                "parameters": [
                    {
                        "description": "auth model",
                        "name": "auth_model",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/co.AuthModel"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/service.Response"
                        }
                    }
                }
            }
        },
        "/auth/me": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "获取认证的自己",
                "parameters": [
                    {
                        "description": "get auth self",
                        "name": "auth_credit",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/co.AuthCredit"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/service.Response"
                        }
                    }
                }
            }
        },
        "/daily/image": {
            "get": {
                "produces": [
                    "image/jpeg"
                ],
                "summary": "随机图片",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/service.Response"
                        }
                    }
                }
            }
        },
        "/daily/sentence": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "summary": "一句话",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/service.Response"
                        }
                    }
                }
            }
        },
        "/decode_verify_code": {
            "post": {
                "consumes": [
                    "image/gif"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "验证码识别",
                "parameters": [
                    {
                        "type": "file",
                        "description": "image of verify code",
                        "name": "img",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/service.Response"
                        }
                    }
                }
            }
        },
        "/mini_program/add_hermann_memorial": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "summary": "添加背单词的任务",
                "parameters": [
                    {
                        "description": "data",
                        "name": "addData",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/co.AddHermannMemorial"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/service.Response"
                        }
                    }
                }
            }
        },
        "/mini_program/change_notification": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "summary": "更新创建一个notification",
                "parameters": [
                    {
                        "description": "one notification",
                        "name": "notification",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/co.Notification"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/service.Response"
                        }
                    }
                }
            }
        },
        "/mini_program/config_menu": {
            "post": {
                "summary": "配置菜单项",
                "parameters": [
                    {
                        "description": "dispose menus",
                        "name": "menus",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/co.Menus"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/service.Response"
                        }
                    }
                }
            }
        },
        "/mini_program/get_hermann_memorial": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "summary": "背单词：今天的任务",
                "parameters": [
                    {
                        "type": "string",
                        "name": "token",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/service.Response"
                        }
                    }
                }
            }
        },
        "/mini_program/get_notifications": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "summary": "获取notification",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/service.Response"
                        }
                    }
                }
            }
        },
        "/mini_program/get_sponsors": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "summary": "查看赞助我的人",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/service.Response"
                        }
                    }
                }
            }
        },
        "/student/scores": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "summary": "获取学生的成绩",
                "parameters": [
                    {
                        "type": "string",
                        "name": "token",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/service.Response"
                        }
                    }
                }
            }
        },
        "/student/update_edu_account": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "summary": "更新学生的信息",
                "parameters": [
                    {
                        "description": "update edu account info",
                        "name": "auth",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/co.EduAccount"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/service.Response"
                        }
                    }
                }
            }
        },
        "/students/{studentId}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "获取当前用户的学生信息",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "student id",
                        "name": "studentId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/service.Response"
                        }
                    }
                }
            }
        },
        "/thinking/list": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "值得深思的句子",
                "parameters": [
                    {
                        "description": "page size",
                        "name": "paging",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/co.PageLimitOffset"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/service.Response"
                        }
                    }
                }
            }
        },
        "/trigger/cron": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "定时任务触发器",
                "parameters": [
                    {
                        "description": "job name",
                        "name": "job_name",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/co.TaskName"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/service.Response"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "co.AddHermannMemorial": {
            "type": "object",
            "properties": {
                "start_at": {
                    "type": "string",
                    "example": "2019-01-23 23:12:30"
                },
                "token": {
                    "type": "string",
                    "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOjEsImV4cCI6MTU4NjgzNTA3NiwiaXNzIjoiY19naW4ifQ.W8BQ2Xy0Z_t4-iVmTCtvo7r3ZYZxZBUjPPSra9Q6Kks"
                },
                "total_unit": {
                    "type": "integer",
                    "example": 39
                },
                "unit": {
                    "type": "integer",
                    "example": 2
                }
            }
        },
        "co.AuthCredit": {
            "type": "object",
            "properties": {
                "token": {
                    "type": "string",
                    "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOjEsImV4cCI6MTU4NjgzNTA3NiwiaXNzIjoiY19naW4ifQ.W8BQ2Xy0Z_t4-iVmTCtvo7r3ZYZxZBUjPPSra9Q6Kks"
                }
            }
        },
        "co.AuthModel": {
            "type": "object",
            "properties": {
                "device_type": {
                    "type": "integer",
                    "example": 2
                },
                "openid": {
                    "type": "string",
                    "example": "openid_xxsd"
                },
                "sign": {
                    "type": "string",
                    "example": "559EB671B3E536C8B1705EA9BD90FCFE"
                }
            }
        },
        "co.EduAccount": {
            "type": "object",
            "properties": {
                "password": {
                    "type": "string",
                    "example": "34"
                },
                "student_number": {
                    "type": "string",
                    "example": "1923"
                },
                "token": {
                    "type": "string",
                    "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOjEsImV4cCI6MTU4NjgzNTA3NiwiaXNzIjoiY19naW4ifQ.W8BQ2Xy0Z_t4-iVmTCtvo7r3ZYZxZBUjPPSra9Q6Kks"
                }
            }
        },
        "co.Menu": {
            "type": "object",
            "properties": {
                "action_type": {
                    "type": "integer",
                    "example": 2
                },
                "action_value": {
                    "type": "string",
                    "example": "action value"
                },
                "desp": {
                    "type": "string",
                    "example": "这是一个菜单的描述"
                },
                "icon": {
                    "type": "string",
                    "example": "icon"
                },
                "title": {
                    "type": "string",
                    "example": "标题"
                }
            }
        },
        "co.Menus": {
            "type": "object",
            "properties": {
                "menus": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/co.Menu"
                    }
                },
                "token": {
                    "type": "string",
                    "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOjEsImV4cCI6MTU4NjgzNTA3NiwiaXNzIjoiY19naW4ifQ.W8BQ2Xy0Z_t4-iVmTCtvo7r3ZYZxZBUjPPSra9Q6Kks"
                }
            }
        },
        "co.Notification": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string",
                    "example": "lalala"
                },
                "end_at": {
                    "type": "string",
                    "example": "2029-01-23 23:12:30"
                },
                "id": {
                    "type": "integer",
                    "example": 18
                },
                "start_at": {
                    "type": "string",
                    "example": "2019-01-23 23:23:34"
                },
                "token": {
                    "type": "string",
                    "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOjEsImV4cCI6MTU4NjgzNTA3NiwiaXNzIjoiY19naW4ifQ.W8BQ2Xy0Z_t4-iVmTCtvo7r3ZYZxZBUjPPSra9Q6Kks"
                }
            }
        },
        "co.PageLimitOffset": {
            "type": "object",
            "properties": {
                "page": {
                    "type": "integer",
                    "example": 1
                },
                "size": {
                    "type": "integer",
                    "example": 100
                }
            }
        },
        "co.TaskName": {
            "type": "object",
            "properties": {
                "job_name": {
                    "type": "string",
                    "example": "sign_baidu_tieba"
                }
            }
        },
        "service.Response": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "type": "object"
                },
                "msg": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "1.0",
	Host:        "localhost:8654",
	BasePath:    "/api/v1",
	Schemes:     []string{},
	Title:       "My Server cgin",
	Description: "this is a custom server of my interesting.",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
