basePath: /api/v1
definitions:
  co.AddHermannMemorial:
    properties:
      start_at:
        example: "2019-01-23 23:12:30"
        type: string
      total_unit:
        example: 39
        type: integer
      unit:
        example: 2
        type: integer
    type: object
  co.AuthModel:
    properties:
      device_type:
        example: 2
        type: integer
      openid:
        example: openid_xxsd
        type: string
      sign:
        example: 559EB671B3E536C8B1705EA9BD90FCFE
        type: string
    type: object
  co.EduAccount:
    properties:
      password:
        example: "34"
        type: string
      student_number:
        example: "1923"
        type: string
    type: object
  co.Menu:
    properties:
      action_type:
        example: 2
        type: integer
      action_value:
        example: action value
        type: string
      desp:
        example: 这是一个菜单的描述
        type: string
      icon:
        example: icon
        type: string
      title:
        example: 标题
        type: string
    type: object
  co.Menus:
    properties:
      menus:
        items:
          $ref: '#/definitions/co.Menu'
        type: array
    type: object
  co.Notification:
    properties:
      content:
        example: lalala
        type: string
      end_at:
        example: "2029-01-23 23:12:30"
        type: string
      id:
        example: 18
        type: integer
      start_at:
        example: "2019-01-23 23:23:34"
        type: string
    type: object
  co.PageLimitOffset:
    properties:
      page:
        example: 1
        type: integer
      size:
        example: 100
        type: integer
    type: object
  co.TaskName:
    properties:
      job_name:
        example: sign_baidu_tieba
        type: string
    type: object
  service.Response:
    properties:
      code:
        type: integer
      data:
        type: object
      msg:
        type: string
    type: object
host: localhost:8654
info:
  contact: {}
  description: this is a custom server of my interesting.
  license: {}
  title: My Server cgin
  version: "1.0"
paths:
  /auth/login:
    post:
      consumes:
      - application/json
      parameters:
      - description: auth model
        in: body
        name: auth_model
        required: true
        schema:
          $ref: '#/definitions/co.AuthModel'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/service.Response'
      summary: 登录
  /auth/me:
    post:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/service.Response'
      security:
      - ApiKeyAuth: []
      summary: 获取认证的自己
  /daily/image:
    get:
      produces:
      - image/jpeg
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/service.Response'
      security:
      - ApiKeyAuth: []
      summary: 随机图片
  /daily/sentence:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/service.Response'
      security:
      - ApiKeyAuth: []
      summary: 一句话
  /decode_verify_code:
    post:
      consumes:
      - image/gif
      parameters:
      - description: image of verify code
        in: formData
        name: img
        required: true
        type: file
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/service.Response'
      summary: 验证码识别
  /mini_program/add_hermann_memorial:
    post:
      parameters:
      - description: data
        in: body
        name: addData
        required: true
        schema:
          $ref: '#/definitions/co.AddHermannMemorial'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/service.Response'
      security:
      - ApiKeyAuth: []
      summary: 添加背单词的任务
  /mini_program/change_notification:
    post:
      parameters:
      - description: one notification
        in: body
        name: notification
        required: true
        schema:
          $ref: '#/definitions/co.Notification'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/service.Response'
      security:
      - ApiKeyAuth: []
      summary: 更新创建一个notification
  /mini_program/config_menu:
    post:
      parameters:
      - description: dispose menus
        in: body
        name: menus
        required: true
        schema:
          $ref: '#/definitions/co.Menus'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/service.Response'
      security:
      - ApiKeyAuth: []
      summary: 配置菜单项
  /mini_program/get_hermann_memorial:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/service.Response'
      security:
      - ApiKeyAuth: []
      summary: 背单词：今天的任务
  /mini_program/get_notifications:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/service.Response'
      security:
      - ApiKeyAuth: []
      summary: 获取notification
  /mini_program/get_sponsors:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/service.Response'
      summary: 查看赞助我的人
  /mini_program/send_template_msg:
    get:
      parameters:
      - description: 用户的open id
        in: query
        name: open_id
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/service.Response'
      summary: 发送微信小程序订阅消息
  /scores:
    get:
      parameters:
      - description: id of student
        in: query
        name: studentId
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/service.Response'
      security:
      - ApiKeyAuth: []
      summary: 获取学生的成绩
  /students/{studentId}:
    get:
      parameters:
      - description: student id
        in: path
        name: studentId
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/service.Response'
      security:
      - ApiKeyAuth: []
      summary: 获取当前用户的学生信息
  /students/update_edu_account:
    post:
      parameters:
      - description: update edu account info
        in: body
        name: auth
        required: true
        schema:
          $ref: '#/definitions/co.EduAccount'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/service.Response'
      summary: 更新学生的信息
  /thinking/list:
    post:
      consumes:
      - application/json
      parameters:
      - description: page size
        in: body
        name: paging
        required: true
        schema:
          $ref: '#/definitions/co.PageLimitOffset'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/service.Response'
      security:
      - ApiKeyAuth: []
      summary: 值得深思的句子
  /trigger/cron:
    post:
      consumes:
      - application/json
      parameters:
      - description: 任务名称
        in: body
        name: job_name
        required: true
        schema:
          $ref: '#/definitions/co.TaskName'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/service.Response'
      security:
      - ApiKeyAuth: []
      summary: 定时任务触发器
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
