basePath: /api
definitions:
  co.AddHermannMemorial:
    properties:
      start_at:
        $ref: '#/definitions/util.JSONTime'
        type: object
      token:
        example: tokne_example.asdass
        type: string
      total_unit:
        example: 39
        type: integer
      unit:
        example: 2
        type: integer
    type: object
  co.AuthCredit:
    properties:
      token:
        example: tokne_example.asdass
        type: string
    type: object
  co.AuthModel:
    properties:
      device_type:
        example: 1
        type: integer
      openid:
        example: aqe
        type: string
      sign:
        example: ewe
        type: string
      token:
        example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOjgsImV4cCI6MTU2MjQ2NTY0MSwiaXNzIjoiY2NsYSJ9.J3QXF3tZlvzyWvx8VG9EibUIr5mHK0xg3mjxY8LGhk8
        type: string
    type: object
  co.PageLimitOffset:
    properties:
      page:
        example: 1
        type: integer
      size:
        example: 100
        type: integer
    type: object
  co.TaskName:
    properties:
      job_name:
        example: sign_baidu_tieba
        type: string
    type: object
  service.Response:
    properties:
      code:
        type: integer
      data:
        type: object
      msg:
        type: string
    type: object
  util.JSONTime:
    type: object
host: localhost:8654
info:
  contact: {}
  description: this is a custom server of my interesting.
  license: {}
  title: My Server cgin
  version: "1.0"
paths:
  /auth/login:
    post:
      consumes:
      - application/json
      parameters:
      - description: auth model
        in: body
        name: auth_model
        required: true
        schema:
          $ref: '#/definitions/co.AuthModel'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/service.Response'
      summary: 登录
  /auth/me:
    post:
      consumes:
      - application/json
      parameters:
      - description: get auth self
        in: body
        name: auth_credit
        required: true
        schema:
          $ref: '#/definitions/co.AuthCredit'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/service.Response'
      summary: 获取认证的自己
  /daily_image:
    get:
      produces:
      - image/jpeg
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/service.Response'
      summary: 随机图片
  /daily_sentence:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/service.Response'
      summary: 一句话
  /mini_program/add_hermann_memorial:
    post:
      parameters:
      - description: data
        in: body
        name: addData
        required: true
        schema:
          $ref: '#/definitions/co.AddHermannMemorial'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/service.Response'
      summary: 添加背单词的任务
  /mini_program/get_hermann_memorial:
    get:
      parameters:
      - in: query
        name: token
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/service.Response'
      summary: 背单词：今天的任务
  /thinking/list:
    post:
      consumes:
      - application/json
      parameters:
      - description: page size
        in: body
        name: paging
        required: true
        schema:
          $ref: '#/definitions/co.PageLimitOffset'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/service.Response'
      summary: 值得深思的句子
  /trigger/cron:
    post:
      consumes:
      - application/json
      parameters:
      - description: job name
        in: body
        name: job_name
        required: true
        schema:
          $ref: '#/definitions/co.TaskName'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/service.Response'
      summary: 定时任务触发器
swagger: "2.0"
