basePath: /api/v1
definitions:
  co.AddHermannMemorial:
    properties:
      start_at:
        example: "2019-01-23 23:12:30"
        type: string
      total_unit:
        example: 39
        type: integer
      unit:
        example: 2
        type: integer
    type: object
  co.AuthModel:
    properties:
      device_type:
        example: 2
        type: integer
      openid:
        example: openid_xxsd
        type: string
      password:
        example: x
        type: string
      sign:
        example: 67807AFF5A99880726B74D03F5A8F78C
        type: string
      username:
        example: cc
        type: string
    type: object
  co.EduAccount:
    properties:
      password:
        example: "34"
        type: string
      student_number:
        example: "1923"
        type: string
    type: object
  co.IndexConfig:
    properties:
      image_style:
        example: fit
        type: string
      image_url:
        example: http://ww1.sinaimg.cn/thumbnail/005uwVPtly1gcyif5da9lj305k05kjrb.jpg
        type: string
      motto:
        example: 好好活着每一天
        type: string
      slogan:
        example: 今天又是美好的一天
        type: string
    type: object
  co.Menu:
    properties:
      action_type:
        example: 2
        type: integer
      action_value:
        example: action value
        type: string
      desp:
        example: 这是一个菜单的描述
        type: string
      icon:
        example: icon
        type: string
      title:
        example: 标题
        type: string
    type: object
  co.Menus:
    properties:
      menus:
        items:
          $ref: '#/definitions/co.Menu'
        type: array
    type: object
  co.Notification:
    properties:
      content:
        example: lalala
        type: string
      end_at:
        example: "2029-01-23 23:12:30"
        type: string
      id:
        example: 18
        type: integer
      start_at:
        example: "2019-01-23 23:23:34"
        type: string
    type: object
  co.PageLimitOffset:
    properties:
      page:
        example: 1
        type: integer
      size:
        example: 100
        type: integer
    type: object
  service.Response:
    properties:
      code:
        type: integer
      data:
        type: object
      msg:
        type: string
    type: object
host: localhost:8654
info:
  contact: {}
  description: 小程序【Retain吧】的服务端代码，其他小的功能
  license: {}
  title: 小程序cgogo的服务端
  version: "1.0"
paths:
  /auth/login:
    post:
      consumes:
      - application/json
      parameters:
      - description: 认证的信息
        in: body
        name: auth_model
        required: true
        schema:
          $ref: '#/definitions/co.AuthModel'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/service.Response'
      summary: 登录
      tags:
      - Auth
  /auth/me:
    post:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/service.Response'
      security:
      - ApiKeyAuth: []
      summary: 获取认证的自己
      tags:
      - Auth
  /daily/images:
    get:
      produces:
      - image/jpeg
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/service.Response'
      security:
      - ApiKeyAuth: []
      summary: 随机图片
      tags:
      - Daily
  /daily/sentences:
    get:
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/service.Response'
      security:
      - ApiKeyAuth: []
      summary: 一句话
      tags:
      - Daily
  /decode_verify_code:
    post:
      consumes:
      - image/gif
      parameters:
      - description: image of verify code
        in: formData
        name: img
        required: true
        type: file
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/service.Response'
      summary: 验证码识别
      tags:
      - 验证码识别
  /health_check/mem:
    get:
      description: 查看系统的内存信息
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/service.Response'
      summary: 系统健康检查
      tags:
      - 系统信息
  /mini_program/hermann_memorials:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/service.Response'
      security:
      - ApiKeyAuth: []
      summary: 背单词：今天的任务
      tags:
      - 背单词
    post:
      parameters:
      - description: data
        in: body
        name: addData
        required: true
        schema:
          $ref: '#/definitions/co.AddHermannMemorial'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/service.Response'
      security:
      - ApiKeyAuth: []
      summary: 添加背单词的任务
      tags:
      - 背单词
  /mini_program/index_config:
    post:
      consumes:
      - application/json
      parameters:
      - description: 小程序首页配置
        in: body
        name: config
        required: true
        schema:
          $ref: '#/definitions/co.IndexConfig'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/service.Response'
      security:
      - ApiKeyAuth: []
      summary: 首页slogan image等的配置信息
      tags:
      - Mini program
  /mini_program/index_preferences:
    get:
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/service.Response'
      security:
      - ApiKeyAuth: []
      summary: 首页的配置
      tags:
      - Mini program
  /mini_program/menus:
    post:
      parameters:
      - description: 配置小程序首页的菜单项
        in: body
        name: menus
        required: true
        schema:
          $ref: '#/definitions/co.Menus'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/service.Response'
      security:
      - ApiKeyAuth: []
      summary: 配置菜单项
      tags:
      - Mini program
  /mini_program/notifications:
    get:
      parameters:
      - in: query
        name: page
        type: integer
      - in: query
        name: size
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/service.Response'
      security:
      - ApiKeyAuth: []
      summary: 获取notifications 分页查询
      tags:
      - Mini program
    put:
      parameters:
      - description: one notification
        in: body
        name: notification
        required: true
        schema:
          $ref: '#/definitions/co.Notification'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/service.Response'
      security:
      - ApiKeyAuth: []
      summary: 更新创建一个notification
      tags:
      - Mini program
  /mini_program/send_template_msg:
    get:
      parameters:
      - description: 用户的open id
        in: query
        name: open_id
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/service.Response'
      security:
      - ApiKeyAuth: []
      summary: 发送微信小程序订阅消息
      tags:
      - Mini program
  /mini_program/sponsors:
    get:
      parameters:
      - in: query
        name: page
        type: integer
      - in: query
        name: size
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/service.Response'
      security:
      - ApiKeyAuth: []
      summary: 查看赞助我的人
      tags:
      - Mini program
  /scores:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/service.Response'
      security:
      - ApiKeyAuth: []
      summary: 获取学生的成绩
      tags:
      - Student
  /students/{studentId}:
    get:
      parameters:
      - description: student id
        in: path
        name: studentId
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/service.Response'
      security:
      - ApiKeyAuth: []
      summary: 获取当前用户的学生信息
      tags:
      - Student
  /students/update_edu_account:
    post:
      parameters:
      - description: update edu account info
        in: body
        name: auth
        required: true
        schema:
          $ref: '#/definitions/co.EduAccount'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/service.Response'
      security:
      - ApiKeyAuth: []
      summary: 更新学生的信息
      tags:
      - Student
  /thinking:
    get:
      consumes:
      - application/json
      parameters:
      - in: query
        name: page
        type: integer
      - in: query
        name: size
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/service.Response'
      security:
      - ApiKeyAuth: []
      summary: 值得深思的句子
      tags:
      - 思考
  /trigger/tasks:
    get:
      consumes:
      - application/json
      parameters:
      - description: 任务名称
        enum:
        - sign_baidu_tieba
        - sync_student_score
        in: query
        name: job_name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "202":
          description: Accepted
          schema:
            $ref: '#/definitions/service.Response'
      security:
      - ApiKeyAuth: []
      summary: 定时任务触发器
      tags:
      - Trigger
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
